### ISSUE TITLE
Not visible in VSCode marketplace

### ISSUE THREAD

**Issue by brandon-blb** [odoo/odoo-ls#55]
Good day.

I do not see this extension in the VS Code marketplace. I do have the latest VS Code version.
Has this not been published yet?

Thank you in advance

**Comment by fda-odoo** [comment]
Hello,

Indeed the publication took some time, but this is now done: you can find the package on the marketplace:
https://marketplace.visualstudio.com/items?itemName=Odoo.odoo
and on open-vsx:
https://open-vsx.org/extension/Odoo/odoo

I hope you'll already appreciate this early version :)

**Comment by brandon-blb** [comment]
Thank you. I managed to find the extension. Very excited about this extension 😁

**Comment by jeffery9** [comment]
can't install this via vscode marketplace, report 

> Can't install release version of 'odoo.odoo' extension because it has no release version.

**Comment by fda-odoo** [comment]
Hello @jeffery9 ,

Indeed the extension has no release at this point, only a pre-release version. We will publish a release version only when we think the tool is totally reliable.
To install the pre-release version, you have to select the arrow next to the "install" button and select "pre-release" version.
